//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Latoken.Api.Client.Library.Dto.Rest;
using System;

namespace LatokenMauiClient
{
    [Serializable]
    public class UserProfile
    {
        public string ProfileName { get; set; }
        public string ApiKey { get; set; }
        public string ApiSecret { get; set; }
        public string Memo { get; set; }
        public string  UserId { get; set; }
    }
}